// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3YRG7PvKYe35edGN5Kyw4yZx8QaVkkdY',
    appId: '1:269718380110:web:1dc5f69e6ae4d7bd54ad1f',
    messagingSenderId: '269718380110',
    projectId: 'datacure-5e5e5',
    authDomain: 'datacure-5e5e5.firebaseapp.com',
    storageBucket: 'datacure-5e5e5.appspot.com',
    measurementId: 'G-PSD11VR70B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChuWpYHuxK0UmCGwAZot3EqO0NNxxolVA',
    appId: '1:269718380110:android:4851e6fb33ea3a3a54ad1f',
    messagingSenderId: '269718380110',
    projectId: 'datacure-5e5e5',
    storageBucket: 'datacure-5e5e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJpkuyD1wwzJ5DWEqJP1HRq1ptw4MbDLE',
    appId: '1:269718380110:ios:c51d5bb24a29063554ad1f',
    messagingSenderId: '269718380110',
    projectId: 'datacure-5e5e5',
    storageBucket: 'datacure-5e5e5.appspot.com',
    iosClientId: '269718380110-iugteeki9u5j4on4k1cih3bud9uq0b8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.datacure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJpkuyD1wwzJ5DWEqJP1HRq1ptw4MbDLE',
    appId: '1:269718380110:ios:c51d5bb24a29063554ad1f',
    messagingSenderId: '269718380110',
    projectId: 'datacure-5e5e5',
    storageBucket: 'datacure-5e5e5.appspot.com',
    iosClientId: '269718380110-iugteeki9u5j4on4k1cih3bud9uq0b8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.datacure',
  );
}
